name: Infinite Aternos Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

# Отменяет предыдущие запущенные процессы этого же воркфлоу
concurrency:
  group: aternos-bot-group
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Quick Install
      run: npm install --no-audit

    - name: Run Bot Node.js
      env:
        ATERNOS_IP: ${{ secrets.ATERNOS_IP }}
        ATERNOS_PORT: ${{ secrets.ATERNOS_PORT }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: node index.js
